### ISSUE TITLE
Is this still usable?

### ISSUE THREAD

**Issue by skybur** [FaisalAbid/segment-analytics-flutter#1]
Hello, 
I want to integrate my app with segment analytics. I'm wondering if I should use this or create platform plugin. Is this still usable?

Thanks!

**Comment by sgelves** [comment]
I would recommend you writing your own plugin, otherwise using an http api would make you lose valuable tracking information.

**Comment by skybur** [comment]
> 
> 
> I would recommend you writing your own plugin, otherwise using an http api would make you lose valuable tracking information.

Yeah, that's what I currently do!
Thanks for the suggestion.
